version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "owntracks-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yny4xljliheg"
s3_prefix = "owntracks-lambda"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
