AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs8.10
    Environment:
      Variables:
        DATA_BUCKET: !Ref DataBucket
        CORS_ORIGIN: https://romantic-brattain-ece9de.netlify.com

Resources:
  PublishFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/publish.js
      Handler: publish.handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
      Events:
        Publish:
          Type: Api
          Properties:
            Path: /publish
            Method: post
  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/list.js
      Handler: list.handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
      Events:
        Publish:
          Type: Api
          Properties:
            Path: /list
            Method: get
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get.js
      Handler: get.handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
      Events:
        Publish:
          Type: Api
          Properties:
            Path: /get/{date}
            Method: get
  DataBucket:
    Type: AWS::S3::Bucket

Outputs:
  Api:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
