AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    CodeUri: .
    Runtime: nodejs8.10
    Environment:
      Variables:
        DATA_BUCKET: !Ref DataBucket

Resources:
  PublishFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/publish.handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
      Events:
        Publish:
          Type: Api
          Properties:
            Path: /publish
            Method: post
  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/list.handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
      Events:
        Publish:
          Type: Api
          Properties:
            Path: /list
            Method: get
  DataBucket:
    Type: AWS::S3::Bucket

Outputs:
  Api:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
