AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DATA_BUCKET: !Ref DataBucket

Resources:
  PublishFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/app.handler
      Runtime: nodejs8.10
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
      Events:
        Publish:
          Type: Api
          Properties:
            Path: /publish
            Method: post
  DataBucket:
    Type: AWS::S3::Bucket

Outputs:
  Api:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
